[package]
name = "json_parser"
version = "0.5.0"
edition = "2018"
build = "build.rs"

[dependencies]
env_logger = "0.9.0"
id_tree = "1.8.0"
id_tree_layout = "2.0.3"
log = "0.4.16"
miette = { version = "4.3.0", features = ["fancy"] }
# TODO: parol_runtime = { path = "../../crates/parol_runtime" }
parol_runtime = "0.5.9"
thiserror = "1.0.30"

[build-dependencies]
# TODO: parol = { path = "../../crates/parol" }
parol = "0.6.1"
