[package]
name = "parol"
version = "0.1.8"
authors = ["Jörg Singer <singer.joerg@gmx.de>"]
description = "LL(k) parser generator for Rust."
documentation = "https://docs.rs/parol"
repository = "https://github.com/jsinger67/parol"
readme = "README.md"
keywords = ["parser", "parsing", "parser-generator", "LLk"]
categories = ["algorithms", "parsing", "Parsing tools"]
license = "MIT"
edition = "2018"

[dependencies]
bart = "0.1.4"
bart_derive = "0.1.4"
env_logger = "0.9.0"
error-chain = "0.12.4"
id_tree = "1.8.0"
id_tree_layout = "2.0.2"
lazy_static = "1.4.0"
log = "0.4.14"
parol_runtime = "0.1.3"
petgraph = "0.6.0"
regex = "1.5.4"
serde = "1.0.126"
serde_derive = "1.0.115"
serde_json = "1.0.64"

[dependencies.clap]
version = "2.33"
default-features = false
features = [ "suggestions", "color", "yaml" ]


[profile.release]
debug = true
