[package]
name = "basic"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.11.1"
env_logger = "0.9.0"
function_name = "0.3.0"
id_tree = "^1.8"
id_tree_layout = "2.0.3"
lazy_static = "^1.4"
log = "0.4.14"
miette = { version = "^4.0", features = ["fancy"] }
parol_runtime = "0.6.0"
thiserror = "^1.0"

[build-dependencies]
parol = "0.10.0"

[dev-dependencies]
regex = "1.5.5"

