[package]
name = "json_parser"
version = "0.1.3"
edition = "2018"

[dependencies]
env_logger = "0.9.0"
error-chain = "0.12.4"
id_tree = "1.8.0"
id_tree_layout = "2.0.2"
lazy_static = "1.4.0"
log = "0.4.14"
parol_runtime = "0.2.3"
