[workspace]

resolver = "2"

members = [
  "crates/*",
  "examples/basic_interpreter",
  "examples/json_parser",
  "examples/json_parser_auto",
  "examples/oberon2",
  "examples/toml"
]

exclude = [
  "examples/boolean_parser",
  "examples/calc",
  "examples/calc_auto",
  "examples/json",
  "examples/keywords",
  "examples/keywords2",
  "examples/list",
  "examples/list_auto",
  "examples/oberon_0",
  "examples/scanner_states",
  "crates/parol/tests/snapshots/bin",
  "crates/parol/tests/snapshots/lib",
]

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.1", features = [ "derive", "cargo" ] }
derive_builder = "0.12.0"
derive-new = "0.5.9"
env_logger = "0.10.0"
function_name = "0.3.0"
id_tree = "1.8"
id_tree_layout = "2"
log = "0.4.17"
once_cell = "1.16"
regex = "1.7"
thiserror = "1.0"

[profile.release.package.parol]
debug = true
opt-level = 3

[profile.release.package.parol-ls]
debug = true

[profile.release.package.json_parser]
debug = true

[profile.release.package.json_parser_auto]
debug = true
opt-level = 3

[profile.release.package.oberon2]
debug = true
opt-level = 3

# Optimized build performance
[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3

# Currently cargo does not support lto setting per crate
# https://github.com/rust-lang/cargo/issues/9330
[profile.release]
lto = true
