[workspace]

resolver = "2"

members = [
  "crates/*",
  "examples/*",
]

exclude = [
  "examples/boolean_parser",
  "examples/calc",
  "examples/calc_auto",
  "examples/json",
  "examples/keywords",
  "examples/keywords2",
  "examples/list",
  "examples/list_auto",
  "examples/oberon_0",
  "examples/scanner_states",
]
