[package]
name = "parol"
version = "0.5.0"
authors = ["Jörg Singer <singer.joerg@gmx.de>"]
description = "LL(k) parser generator for Rust."
documentation = "https://docs.rs/parol"
repository = "https://github.com/jsinger67/parol"
readme = "README.md"
keywords = ["parser", "parsing", "parser-generator", "LLk"]
categories = ["algorithms", "parsing", "Parsing tools"]
license = "MIT"
edition = "2018"
# Gives tools poor names (without prefixes). See issue #2
autobins = false
default-run = "parol"

[dependencies]
bart = "0.1.4"
bart_derive = "0.1.4"
env_logger = "0.9.0"
id_tree = "1.8.0"
id_tree_layout = "2.0.2"
lazy_static = "1.4.0"
log = "0.4.14"
parol_runtime = "0.5.2"
petgraph = "0.6.0"
regex = "1.5.4"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.69"
miette = { version = "3.2.0", features = ["fancy"] }

[dependencies.clap]
version = "2.33.3"
default-features = false
features = [ "suggestions", "color", "yaml" ]


[profile.release]
debug = true

[[bin]]
name = "parol"

# Prefix all the tool names with parol-<tool> to avoid polluting the path
#
# Otherwise `cargo install` will install them directly into $PATH
# See issue #2
#
# The main binary picks up these subcommands automatically and runs them as external tools.
[[bin]]
name = "parol-calculate-k"
path = "src/bin/calculate_k.rs"

[[bin]]
name = "parol-calculate-k-tuples"
path = "src/bin/calculate_k_tuples.rs"

[[bin]]
name = "parol-decidable"
path = "src/bin/decidable.rs"

[[bin]]
name = "parol-first"
path = "src/bin/first.rs"

[[bin]]
name = "parol-follow"
path = "src/bin/follow.rs"

[[bin]]
name = "parol-format"
path = "src/bin/format.rs"

[[bin]]
name = "parol-left-factor"
path = "src/bin/left_factor.rs"

[[bin]]
name = "parol-left-recursions"
path = "src/bin/left_recursions.rs"

[[bin]]
name = "parol-productivity"
path = "src/bin/productivity.rs"

[[bin]]
name = "parol-serialize"
path = "src/bin/serialize.rs"
