[workspace]

resolver = "2"

members = [
  "crates/*",
  "examples/basic_interpreter",
  "examples/json_parser_auto",
  "examples/oberon2"
]

exclude = [
  "examples/boolean_parser",
  "examples/calc",
  "examples/calc_auto",
  "examples/json",
  "examples/keywords",
  "examples/keywords2",
  "examples/list",
  "examples/list_auto",
  "examples/oberon_0",
  "examples/scanner_states",
]

[profile.release.package.parol]
debug = true
opt-level = 3

[profile.release.package.parol-ls]
debug = true

[profile.release.package.json_parser]
debug = true

[profile.release.package.json_parser_auto]
debug = true
opt-level = 3

[profile.release.package.oberon2]
debug = true
opt-level = 3

# Currently cargo does not support lto setting per crate
# https://github.com/rust-lang/cargo/issues/9330
[profile.release]
lto = true
