[package]
name = "parol-ls"
version = "0.1.12"
authors = ["Jörg Singer <singer.joerg@gmx.de>"]
description = "Language server for parol parser generator"
documentation = "https://docs.rs/parol-ls"
repository = "https://github.com/jsinger67/parol-ls"
readme = "README.md"
keywords = ["language-server", "parsing", "parser-generator"]
categories = ["algorithms", "parsing", "text-editors"]
license = "MIT"
edition = "2021"
default-run = "parol-ls"

[dependencies]
clap = { version = "^3.2.16", features = [ "derive", "cargo" ] }
derive-new = "0.5.9"
derive_builder = "0.11.2"
env_logger = "0.9.0"
function_name = "0.3.0"
id_tree = "^1.8"
lazy_static = "^1.4"
log = "0.4.17"
lsp-server = "0.6.0"
lsp-types = "0.93.0"
miette = "^5.2"
parol = "0.10.6"
parol_runtime = { version = "0.7.2", features = ["trim_parse_tree"] }
regex = "1.6.0"
serde = "^1.0.142"
serde_json = "^1.0.83"
thiserror = "^1.0.32"

[build-dependencies]
parol = "0.10.6"

[profile.release]
debug = true
