[package]
name = "json_parser_auto"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[dependencies]
env_logger = "0.9.0"
id_tree = "^1.8"
id_tree_layout = "^2.0"
lazy_static = "^1.4"
log = "0.4.14"
miette = { version = "^4.0", features = ["fancy"] }
parol_runtime = { version = "0.5.9", features = ["trim_parse_tree"] }
thiserror = "^1.0"
derive_builder = "0.11.1"

[build-dependencies]
parol = "0.6.1"

[profile.release]
debug = true
