[package]
name = "basic"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.11.2"
env_logger = "0.9.0"
function_name = "0.3.0"
id_tree = "^1.8"
id_tree_layout = "2.0.3"
log = "0.4.14"
miette = { version = "^5.3", features = ["fancy"] }
parol_runtime = { path = "../../crates/parol_runtime", features = ["auto_generation"] }
parol-macros = { path = "../../crates/parol-macros" }
thiserror = "^1.0"

[build-dependencies]
parol = { path = "../../crates/parol" }

[dev-dependencies]
regex = "1.5.5"
