[package]
name = "parol"
version = "0.15.0"
authors = ["Jörg Singer <singer.joerg@gmx.de>"]
description = "LL(k) parser generator for Rust"
default-run = "parol"
documentation = "https://docs.rs/parol"
repository = "https://github.com/jsinger67/parol/tree/main/crates/parol"
readme = "../../README.md"
keywords = ["parser", "parsing", "parser-generator", "LLk"]
categories = ["algorithms", "parsing", "Parsing tools"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
ume = "0.1"
cfg-if = "1.0.0"
clap = { version = "4.0", features = [ "derive", "cargo" ] }
derive_builder = "0.12.0"
env_logger = "0.10.0"
function_name = "0.3.0"
id_tree = "1.8"
id_tree_layout = "2.0"
once_cell = "1.16"
log = "0.4.17"
miette = { version = "5.2.0", features = ["fancy"] }
owo-colors = "3.5.0"
parol-macros = { path = "../parol-macros", version = "0.1.0" }
parol_runtime = { path = "../parol_runtime", version = "0.11.2", features = ["auto_generation"] }
rand = "0.8.5"
rand_regex = "0.15.1"
regex = "1.6"
regex-syntax = "0.6.27"
syn = { version = "1", default-features = false, features = ["full", "parsing"] }
thiserror = "1.0"

[features]
default = ["build"]
# Includes logic for invoking from build.rs script
build = []

[[bin]]
name = "parol"
required-features = ["build"]

[[example]]
name = "boolean_parser"
path = "../../examples/boolean_parser/main.rs"

[[example]]
name = "calc"
path = "../../examples/calc/main.rs"

[[example]]
name = "calc_auto"
path = "../../examples/calc_auto/main.rs"

[[example]]
name = "keywords"
path = "../../examples/keywords/main.rs"

[[example]]
name = "keywords2"
path = "../../examples/keywords2/main.rs"

[[example]]
name = "list"
path = "../../examples/list/main.rs"

[[example]]
name = "list_auto"
path = "../../examples/list_auto/main.rs"

[[example]]
name = "oberon_0"
path = "../../examples/oberon_0/main.rs"

[[example]]
name = "scanner_states"
path = "../../examples/scanner_states/main.rs"

[dev-dependencies]
pretty_assertions = "1.3"
assert_cmd = "2.0"
tempfile = "3"
