[package]
name = "oberon2"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "^0.11"
env_logger = "0.9.0"
function_name = "0.3.0"
id_tree = "^1.8"
lazy_static = "^1.4"
log = "^0.4"
miette = { version = "^5.3", features = ["fancy"] }
parol_runtime = { version = "0.8.1", features = ["trim_parse_tree"] }
parol-macros = "0.1.0"
thiserror = "^1.0"

[build-dependencies]
parol ="0.13.0"

[profile.release]
debug = true
lto = true
opt-level = 3
