[package]
name = "parol-ls"
version = "0.7.0"
authors = ["Jörg Singer <singer.joerg@gmx.de>"]
description = "Language server for parol parser generator"
documentation = "https://docs.rs/parol-ls"
repository = "https://github.com/jsinger67/parol/tree/main/crates/parol-ls"
readme = "README.md"
keywords = ["language-server", "parsing", "parser-generator"]
categories = ["algorithms", "parsing", "text-editors"]
license = "MIT OR Apache-2.0"
edition = "2021"
default-run = "parol-ls"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
derive_builder = { workspace = true }
derive-new = { workspace = true }
env_logger = { workspace = true }
function_name = { workspace = true }
syntree = { workspace = true }
log = { workspace = true }
lsp-server = "0.7.0"
lsp-types = "0.94.0"
once_cell = { workspace = true }
parol = { path = "../parol", version = "0.19.0" }
parol_runtime = { path = "../parol_runtime", version = "0.15.0", features = ["auto_generation"] }
parol-macros = { path = "../parol-macros", version = "0.2.0" }
regex = { workspace = true }
serde = "1.0.152"
serde_json = "1.0.93"
thiserror = { workspace = true }

[build-dependencies]
parol = { path = "../parol", version = "0.19.0" }

[features]
max_level_off   = ["log/max_level_off"]
max_level_error = ["log/max_level_error"]
max_level_warn  = ["log/max_level_warn"]
max_level_info  = ["log/max_level_info"]
max_level_debug = ["log/max_level_debug"]
max_level_trace = ["log/max_level_trace"]
release_max_level_off   = ["log/release_max_level_off"]
release_max_level_error = ["log/release_max_level_error"]
release_max_level_warn  = ["log/release_max_level_warn"]
release_max_level_info  = ["log/release_max_level_info"]
release_max_level_debug = ["log/release_max_level_debug"]
release_max_level_trace = ["log/release_max_level_trace"]
